name: WebDavBackup
version: 'v1.2.6-beta'
main: org.webdavbackup.webDavBackup.WebDavBackup
api-version: '1.20'
commands:
  backup:
    description: Creates a backup of the server
    usage: /backup
    permission: myPlugin.backup
  reloadconfig:
    description: Reloads the configuration file
    usage: /reloadconfig
    permission: myPlugin.reloadconfig