name: WebDavBackup
version: 'v1.2.0-beta'
main: org.webdavbackup.webDavBackup.WebDavBackup
api-version: '1.20'
commands:
  backup:
    description: Creates a backup of the server
    usage: /backup
    permission: myPlugin.backup